# Task 1: Data Cleaning & Preprocessing
**Internship:** SoftNexis Technology   
**Intern Name:** Shubham Jaiswal  
**Domain:** Data Science & Machine Learning Using Python  
**Dataset:** Customers Dataset (1000 records)  
**Objective:** Clean and preprocess raw customer data to make it ready for analysis.

# Step 1: Data Ingestion
Loading the CSV file and taking a first look at the data.

In [1]:
# importing libraries
import numpy as np
import pandas as pd
print("libraries imported successfully!")

libraries imported successfully!

In [2]:
df = pd.read_csv('customers-1000.csv')
print("Dataset loaded sucessfully!")

Dataset loaded sucessfully!

In [3]:
# shape of the dataset
print("shape:", df.shape)
df.head()

shape: (1000, 12)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/

## Initial Data Inspection
Checking column names, data types, and basic statistics before cleaning.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              1000 non-null   int64
 1   Customer Id        1000 non-null   object
 2   First Name         1000 non-null   object
 3   Last Name          1000 non-null   object
 4   Company            1000 non-null   object
 5   City               1000 non-null   object
 6   Country            1000 non-null   object
 7   Phone 1            1000 non-null   object
 8   Phone 2            1000 non-null   object
 9   Email              1000 non-null   object
 10  Subscription Date  1000 non-null   object
 11  Website            1000 non-null   object
dtypes: int64(1), object(11)
memory usage: 93.9+ KB

In [5]:
df.describe(include='all')

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
count,1000.000000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
unique,NaN,1000,536,622,992,983,240,1000,1000,1000,608,973
top,NaN,51732B5b2328015,Larry,Waters,Mercado PLC,Port Gavin,Liechtenstein,+1-278-758-4331,814-860-0941x057,owarner@velasquez.info,2020-11-13,http://www.tapia.com/
freq,NaN,1,6,7,2,2,12,1,1,1,5,3
mean,500.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,288.819436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,250.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,500.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,750.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Step 2: Deduplication
Duplicate rows can affect analysis results, so I'll check and remove them.

In [6]:
print("Duplicate rows found:", df.duplicated().sum())

Duplicate rows found: 0

In [7]:
# drop duplicates
df = df.drop_duplicates()
print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (1000, 12)

# Step 3: Column Management
The `Index` column is just a serial number, pandas handles that automatically.  
`Phone 2` is a secondary number which is not needed for analysis. Dropping both.

In [8]:
df = df.drop(columns=['Index', 'Phone 2'])
print("Remaining columns:", df.columns.tolist())

Remaining columns: ['Customer Id', 'First Name', 'Last Name', 'Company', 'City', 'Country', 'Phone 1', 'Email', 'Subscription Date', 'Website']

## Renaming Columns
Renaming columns to lowercase with underscores — cleaner and easier to work with in code.

In [9]:
df.columns = ['customer_id', 'first_name', 'last_name', 'company', 
              'city', 'country', 'phone', 'email', 'subscription_date', 'website']
print("Renamed columns:", df.columns.tolist())

Renamed columns: ['customer_id', 'first_name', 'last_name', 'company', 'city', 'country', 'phone', 'email', 'subscription_date', 'website']

# Step 4: Missing Value Handling
Let's see if any column has missing/null values.

In [10]:
print("Missing values per column:")
print(df.isna().sum())

Missing values per column:
customer_id          0
first_name           0
last_name            0
company              0
city                 0
country              0
phone                0
email                0
subscription_date    0
website              0
dtype: int64

In [11]:
print("Total missing values:", df.isna().sum().sum())

Total missing values: 0

# Step 5: Data Type Correction 
The `subscription_date` column is stored as a string. Converting it to datetime format

In [12]:
print("Before:", df['subscription_date'].dtype)

Before: object

In [13]:
df['subscription_date'] = pd.to_datetime(df['subscription_date'], errors='coerce')
print("After:", df['subscription_date'].dtype)

After: datetime64[ns]

# Step 6: Format Standardization 
I noticed the following issues:  
- `customer_id` has mixed upper/lowercase letters  
- `email` is not consistently lowercase  
- `first_name`, `last_name`, `city`, `country` need proper title casing  
- Extra whitespace needs to be removed from all text columns

In [14]:
df['customer_id'] = df['customer_id'].str.upper().str.strip()
df['email'] = df['email'].str.lower().str.strip()
df['first_name'] = df['first_name'].str.title().str.strip()
df['last_name'] = df['last_name'].str.title().str.strip()
df['city'] = df['city'].str.title().str.strip()
df['country'] = df['country'].str.title().str.strip()
df['company'] = df['company'].str.strip()
df['website'] = df['website'].str.strip()

print("Text columns standardized!")
df[['customer_id', 'email', 'first_name', 'last_name', 'city', 'country', 'subscription_date', 'company', 'website']].head()

Text columns standardized!

,customer_id,email,first_name,last_name,city,country,subscription_date,company,website
0,DE014D010C7AB0C,marieyates@gomez-spencer.info,Andrew,Goodman,Rowlandberg,Macao,2021-07-26,Stewart-Flynn,http://www.shea.biz/
1,2B54172C8B65EC3,alexandra86@mccoy.com,Alvin,Lane,Bethside,Papua New Guinea,2021-06-24,"Terry, Proctor and Lawrence",http://www.pena-cole.com/
2,D794DD48988D2AC,justincurtis@pierce.org,Jenna,Harding,Moniquemouth,China,2020-04-05,Bailey Group,http://www.booth-reese.biz/
3,3B3AA4ACC68F3BE,adeleon@hubbard.org,Fernando,Ford,Leeborough,Macao,2020-11-29,Moss-Maxwell,http://www.hebert.com/
4,D60DF62AD2AE41E,jesus90@roberson.info,Kara,Woods,Port Jacksonland,Nepal,2022-04-22,Mccarthy-Kelley,http://merritt.com/

## Extracting Subscription Year
Since the date is now properly formatted, I'll extract the year into a  
new column — useful for yearly analysis.

In [15]:
df['subscription_year'] = df['subscription_date'].dt.year
print("Subscription year range:", df['subscription_year'].min(), "to", df['subscription_year'].max())
df[['subscription_date', 'subscription_year']].head()

Subscription year range: 2020 to 2022

  subscription_date  subscription_year
0        2021-07-26               2021
1        2021-06-24               2021
2        2020-04-05               2020
3        2020-11-29               2020
4        2022-04-22               2022

## Final Result
Running final checks to confirm the data is properly cleaned.

In [16]:
print("Final shape:", df.shape)

print("\nMissing values after cleaning:")
print(df.isna().sum())

print("\nDuplicates after cleaning:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Final shape: (1000, 11)

Missing values after cleaning:
customer_id          0
first_name           0
last_name            0
company              0
city                 0
country              0
phone                0
email                0
subscription_date    0
website              0
subscription_year    0
dtype: int64

Duplicates after cleaning: 0

Data types:
customer_id                  object
first_name                   object
last_name                    object
company                      object
city                         object
country                      object
phone                        object
email                        object
subscription_date    datetime64[ns]
website                      object
subscription_year             int32
dtype: object

# Step 7: Saving the Cleaned Dataset
Saving the final cleaned data as a new CSV file.

In [17]:
df.to_csv('cleaned_customers.csv', index=False)
print("Cleaned dataset saved as 'cleaned_customers.csv'!")
df.head()

Cleaned dataset saved as 'cleaned_customers.csv'!

,customer_id,first_name,last_name,company,city,country,phone,email,subscription_date,website,subscription_year
0,DE014D010C7AB0C,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/,2021
1,2B54172C8B65EC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/,2021
2,D794DD48988D2AC,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/,2020
3,3B3AA4ACC68F3BE,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/,2020
4,D60DF62AD2AE41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,jesus90@roberson.info,2022-04-22,http://merritt.com/,2022